cadeauxTwitch/SimulationTwitch.Web.UI/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace SimulationTwitch.Web.UI.Models
{
    public class DefaultDbContext : DbContext
    {
        public DefaultDbContext(DbContextOptions options) : base(options) { }

        protected DefaultDbContext() { }


        // mettre liaison Classe de models avec table base de données
        public DbSet<StreamTwitchModel> StreamsTwitch { get; set; }
        
    }
}

cadeauxTwitch/SimulationTwitch.Web.UI/Models/ErrorViewModel.cs
namespace SimulationTwitch.Web.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

cadeauxTwitch/SimulationTwitch.Web.UI/Models/StreamAddViewModel.cs
using cadeau.api;

namespace SimulationTwitch.Web.UI.Models
{
    public class StreamAddViewModel
    {
        public StreamTwitchModel UnStream { get; set; }
        public int Status { get; set; }
    }
}

cadeauxTwitch/SimulationTwitch.Web.UI/Models/StreamTwitchModel.cs
using cadeau.api;

namespace SimulationTwitch.Web.UI.Models
{
    public class StreamTwitchModel : StreamTwitch
    {
    }
}

cadeauxTwitch/SimulationTwitch.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SimulationTwitch.Web.UI.Models;
using System.Diagnostics;

namespace SimulationTwitch.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

cadeauxTwitch/SimulationTwitch.Web.UI/Controllers/StreamTwitchController.cs
using Microsoft.AspNetCore.Mvc;
using SimulationTwitch.Web.UI.Models;

namespace SimulationTwitch.Web.UI.Controllers
{
    public class StreamTwitchController : Controller
    {
        private readonly DefaultDbContext context;
        


        public StreamTwitchController(DefaultDbContext context)
        {
            this.context = context;
            
        }

        

        public IActionResult Index()
        {
           var query = from item in this.context.StreamsTwitch
                        select item;

            return View(query.ToList());
        }

        public IActionResult NouveauStream()
        {
            return this.View();
        }

        [HttpPost]
       
        public IActionResult NouveauStream(StreamAddViewModel item)
        {
            item.UnStream.Status = item.Status;

            this.context.StreamsTwitch.Add(item.UnStream);

            this.context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

cadeauxTwitch/SimulationTwitch.Web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

cadeauxTwitch/SimulationTwitch.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimulationTwitch.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimulationTwitch.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimulationTwitch.Web.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SimulationTwitch.Web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

cadeauxTwitch/SimulationTwitch.Web.UI/Views/StreamTwitch/Index.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Mon Stream</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
	<script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"></script>
	<style>
		/* Police de caractères globale */
		body {
			font-family: Arial, sans-serif;
		}

		/* styles pour le logo Twitch */
		.logo-twitch {
			display: inline-block;
			height: 50px;
			width: auto;
			margin-right: 10px;
		}

		/* styles pour les icônes de réseaux sociaux */
		.social-icons {
			display: inline-block;
			margin: 0;
			padding: 0;
			list-style: none;
		}

			.social-icons li {
				display: inline-block;
				margin-right: 10px;
			}

				.social-icons li:last-child {
					margin-right: 0;
				}

			.social-icons a {
				display: inline-block;
				height: 50px;
				width: 50px;
				line-height: 50px;
				text-align: center;
				background-color: #000;
				color: #fff;
				border-radius: 50%;
				font-size: 24px;
				text-decoration: none;
			}

				.social-icons a:hover {
					background-color: #6441A4;
					color: #fff;
				}
		/* Style pour l'en-tête */
		header {
			background-color: #1c1c1c;
			color: #fff;
			padding: 20px;
		}

			header h1 {
				margin: 0;
			}

			header ul {
				margin: 0;
				padding: 0;
				list-style: none;
			}

				header ul li {
					display: inline-block;
					margin-right: 20px;
				}

					header ul li a {
						color: #fff;
						text-decoration: none;
					}

						header ul li a:hover {
							border-bottom: 2px solid #fff;
						}

		/* Style pour la section "Ma chaîne" */
		section:first-of-type {
			padding: 40px;
			background-color: #f7f7f7;
		}

		section h2 {
			margin-top: 0;
		}

		section ul {
			margin: 20px 0 0;
			padding: 0;
			list-style: none;
		}

			section ul li {
				display: inline-block;
				margin-right: 20px;
			}

				section ul li a {
					color: #1c1c1c;
					text-decoration: none;
				}

					section ul li a:hover {
						border-bottom: 2px solid #1c1c1c;
					}

		/* Style pour la section "Mon dernier stream" */
		section:nth-of-type(2) {
			padding: 40px;
			background-color: #fff;
		}

		.video-container {
			position: relative;
			padding-bottom: 56.25%;
			height: 0;
		}

			.video-container iframe {
				position: absolute;
				top: 0;
				left: 0;
				width: 100%;
				height: 100%;
			}

		/* Style pour la section "Mon planning de diffusion" */
		section:nth-of-type(3) {
			padding: 40px;
			background-color: #f7f7f7;
		}

		table {
			width: 100%;
			border-collapse: collapse;
		}

			table thead {
				background-color: #1c1c1c;
				color: #fff;
			}

			table th, table td {
				padding: 10px;
				text-align: left;
				border: 1px solid #ccc;
			}

				table td:first-of-type {
					font-weight: bold;
				}

		/* Style pour le pied de page */
		footer {
			background-color: #1c1c1c;
			color: #fff;
			padding: 20px;
			text-align: center;
		}
	</style>
</head>
<body>
	<header>
		<h1>Mon Stream</h1>
		<nav>
			<ul>
				<li><a href="/">Accueil</a></li>
				<li><a href="/about">A propos</a></li>
				<li><a href="/contact">Contact</a></li>
			</ul>
		</nav>
		<img class="logo-twitch" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Twitch_logo_2019.svg/langfr-300px-Twitch_logo_2019.svg.png">
		<ul class="social-icons">
			<li><a href="https://twitter.com/monstream"><i class="fab fa-twitter"></i></a></li>
			<li><a href="https://www.instagram.com/monstream/"><i class="fab fa-instagram"></i></a></li>
			<li><a href="https://www.facebook.com/monstream"><i class="fab fa-facebook"></i></a></li>
		</ul>
	</header>
	<main>
		<section>
			<h2>Ma chaîne</h2>
			<p>Bienvenue sur ma chaîne de streaming !</p>
			<p>Je suis un streamer passionné de jeux vidéo et de technologie, et j'aime partager mes aventures avec ma communauté.</p>
			<p>Vous pouvez me suivre sur les réseaux sociaux pour être informé de mes prochaines diffusions :</p>
			<ul>
				<li><a href="https://twitter.com/monstream">Twitter</a></li>
				<li><a href="https://www.instagram.com/monstream/">Instagram</a></li>
				<li><a href="https://www.facebook.com/monstream">Facebook</a></li>
			</ul>
		</section>
		<section>
			<div style="text-align: center; margin-top: 20px; margin-bottom: 10px;">
				<form asp-action="NouveauStream" asp-area="" asp-controller="StreamTwitch" method="get">
					<button type="submit" style="background-color: red; color: white; font-size: 18px;">Nouveau Stream</button>
				</form>
			</div>




			@if (Model.Count > 0)
			{
				<table>
					<tr><th>Date</th><th>Titre</th><th>Statut</th></tr>
					@foreach (var item in Model)
					{
						<tr>
							<td>@item.DebutStream</td>
							<td>@item.Titre</td>
							<td>
								@switch (item.Status)
								{
									case 1:
										<text>Passé</text>
										break;
									case 2:
										<text>En cours</text>
										break;
									case 3:
										<text>A venir</text>
										break;
									default:
										<text>Inconnu</text>
										break;
								}
							</td>
						</tr>
					}

				</table>
			}
			else
			{
				<h3>Aucun Stream Enregistré</h3>
			}
		
		</section>
		<section>
			<h2>Mon dernier stream</h2>
			<div class="video-container">
				<iframe src="https://www.youtube.com/embed/DLzxrzFCyOs"></iframe>
			</div>
			<p>Voici le replay de mon dernier stream. J'espère que vous avez apprécié le contenu !</p>
			<p>N'hésitez pas à me laisser un commentaire pour me dire ce que vous avez aimé, et ce que je pourrais améliorer pour la prochaine fois.</p>
		</section>
		<section>
			<h2>Mon planning de diffusion</h2>
			<table>
				<thead>
					<tr>
						<th>Jour</th>
						<th>Heure</th>
						<th>Jeu</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Lundi</td>
						<td>20h-22h</td>
						<td>Fortnite</td>
					</tr>
					<tr>
						<td>Mercredi</td>
						<td>18h-20h</td>
						<td>League of Legends</td>
					</tr>
					<tr>
						<td>Vendredi</td>
						<td>21h-23h</td>
						<td>Among Us</td>
					</tr>
				</tbody>
			</table>
			<p>Voici les horaires et les jeux que je vais streamer cette semaine. J'espère vous voir nombreux pour suivre mes aventures !</p>
		</section>
	</main>
	<footer>
		<p>&copy; Mon Stream 2023 - Tous droits réservés</p>
	</footer>
</body>
</html>

cadeauxTwitch/SimulationTwitch.Web.UI/Views/StreamTwitch/NouveauStream.cshtml
<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 20px;
        font-size: 18px;
        background-color: #F4F4F4;
        padding: 20px;
        border-radius: 5px;
    }

    label {
        margin-top: 10px;
        margin-bottom: 5px;
        font-weight: bold;
    }

    input, select {
        padding: 10px;
        border-radius: 5px;
        border: none;
        margin-bottom: 15px;
    }

        input[type="submit"] {
            background-color: #3498DB;
            color: white;
            padding: 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

            input[type="submit"]:hover {
                background-color: #2980B9;
            }

</style>
<form asp-action="NouveauStream" asp-area="" asp-controller="StreamTwitch" method="post">
    <div>
        <label for="Titre">Titre:</label>
        <input type="text" name="UnStream.Titre" required>
    </div>
    <div>
        <label for="DebutStream">Début du stream:</label>
        <input type="datetime-local" name="UnStream.DebutStream" required>
    </div>
    <div>
        <label for="Status">Statut:</label>
        <select name="Status">
            <option value="1">Passé</option>
            <option value="2">En cours</option>
            <option value="3">À venir</option>
        </select>
    </div>
    <div>
        <input type="submit" value="Enregistrer">
    </div>
</form>