cadeauxTwitch/cadeauxTwitch.web.UI/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;
using cadeau.api;

namespace cadeauxTwitch.web.UI.Models
{
    public class DefaultDbContext : DbContext
    {
        public DefaultDbContext(DbContextOptions options) : base(options) { }

        protected DefaultDbContext() { }

        public DbSet<TwitchViewer> TwitchViewers { get; set; }
    }
}

cadeauxTwitch/cadeauxTwitch.web.UI/Models/ErrorViewModel.cs
namespace cadeauxTwitch.web.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

cadeauxTwitch/cadeauxTwitch.web.UI/Models/Viewer.cs
using cadeau.api;

namespace cadeauxTwitch.web.UI.Models
{
    public class Viewer : TwitchViewer
    {
    }
}

cadeauxTwitch/cadeauxTwitch.web.UI/Controllers/HomeController.cs
using cadeauxTwitch.web.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace cadeauxTwitch.web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

cadeauxTwitch/cadeauxTwitch.web.UI/Controllers/ViewerController.cs
using Microsoft.AspNetCore.Mvc;
using cadeauxTwitch.web.UI.Models;
using System.Linq;
using cadeau.api;
using System.Linq.Expressions;

namespace cadeauxTwitch.web.UI.Controllers
{
    public class ViewerController : Controller
    {
        private readonly DefaultDbContext context;

        public ViewerController(DefaultDbContext context)
        {
            this.context = context;
        }

       public IActionResult List(bool estFiltre, List<TwitchViewer> listeViewer)
       {
            List<TwitchViewer> personnes;
            if(estFiltre)
            {
                personnes = listeViewer;
            } else
            {
                var query = from item in this.context.TwitchViewers
                            select item;
                personnes = query.ToList();
            }
            return View(personnes);
       }
       
        public IActionResult ListFidele()
        {
            var query = from item in this.context.TwitchViewers
                        where item.EligibleCadeau == true
                        select item;

            List<TwitchViewer> listeViewer = query.ToList();
            return this.List(true, listeViewer);
        }

        [HttpPost]
        public IActionResult List(string typeFiltre)
        {
            switch (typeFiltre.ToLower())
            {
                case "tous":
                    return this.List(false, new List<TwitchViewer>());
                case "fidele":
                    return this.ListFidele();     
                default:
                    return this.List(false, new List<TwitchViewer>());
            }
        }
    }
}

cadeauxTwitch/cadeauxTwitch.web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

cadeauxTwitch/cadeauxTwitch.web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cadeauxTwitch.web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cadeauxTwitch.web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cadeauxTwitch.web.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - cadeauxTwitch.web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

cadeauxTwitch/cadeauxTwitch.web.UI/Views/Viewer/List.cshtml
@using cadeau.api
@model List<TwitchViewer>


<!DOCTYPE html>
<html>
<head>
	<title>Mon Stream</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
	<script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"></script>
	<style>
		/* Police de caractères globale */
		body {
			font-family: Arial, sans-serif;
		}

		/* styles pour le logo Twitch */
		.logo-twitch {
			display: inline-block;
			height: 50px;
			width: auto;
			margin-right: 10px;
		}

		/* styles pour les icônes de réseaux sociaux */
		.social-icons {
			display: inline-block;
			margin: 0;
			padding: 0;
			list-style: none;
		}

			.social-icons li {
				display: inline-block;
				margin-right: 10px;
			}

				.social-icons li:last-child {
					margin-right: 0;
				}

			.social-icons a {
				display: inline-block;
				height: 50px;
				width: 50px;
				line-height: 50px;
				text-align: center;
				background-color: #000;
				color: #fff;
				border-radius: 50%;
				font-size: 24px;
				text-decoration: none;
			}

				.social-icons a:hover {
					background-color: #6441A4;
					color: #fff;
				}
		/* Style pour l'en-tête */
		header {
			background-color: #1c1c1c;
			color: #fff;
			padding: 20px;
		}

			header h1 {
				margin: 0;
			}

			header ul {
				margin: 0;
				padding: 0;
				list-style: none;
			}

				header ul li {
					display: inline-block;
					margin-right: 20px;
				}

					header ul li a {
						color: #fff;
						text-decoration: none;
					}

						header ul li a:hover {
							border-bottom: 2px solid #fff;
						}

		/* Style pour la section "Ma chaîne" */
		section:first-of-type {
			padding: 40px;
			background-color: #f7f7f7;
		}

		section h2 {
			margin-top: 0;
		}

		section ul {
			margin: 20px 0 0;
			padding: 0;
			list-style: none;
		}

			section ul li {
				display: inline-block;
				margin-right: 20px;
			}

				section ul li a {
					color: #1c1c1c;
					text-decoration: none;
				}

					section ul li a:hover {
						border-bottom: 2px solid #1c1c1c;
					}

		/* Style pour la section "Mon dernier stream" */
		section:nth-of-type(2) {
			padding: 40px;
			background-color: #fff;
		}

		.video-container {
			position: relative;
			padding-bottom: 56.25%;
			height: 0;
		}

			.video-container iframe {
				position: absolute;
				top: 0;
				left: 0;
				width: 100%;
				height: 100%;
			}

		/* Style pour la section "Mon planning de diffusion" */
		section:nth-of-type(3) {
			padding: 40px;
			background-color: #f7f7f7;
		}

		table {
			width: 100%;
			border-collapse: collapse;
		}

			table thead {
				background-color: #1c1c1c;
				color: #fff;
			}

			table th, table td {
				padding: 10px;
				text-align: left;
				border: 1px solid #ccc;
			}

				table td:first-of-type {
					font-weight: bold;
				}

		/* Style pour le pied de page */
		footer {
			background-color: #1c1c1c;
			color: #fff;
			padding: 20px;
			text-align: center;
		}
	</style>
</head>
<body>
	<header>
		<h1>Mon Stream</h1>
		<nav>
			<ul>
				<li><a href="/">Accueil</a></li>
				<li><a href="/about">A propos</a></li>
				<li><a href="/contact">Contact</a></li>
			</ul>
		</nav>
		<img class="logo-twitch" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Twitch_logo_2019.svg/langfr-300px-Twitch_logo_2019.svg.png">
		<ul class="social-icons">
			<li><a href="https://twitter.com/monstream"><i class="fab fa-twitter"></i></a></li>
			<li><a href="https://www.instagram.com/monstream/"><i class="fab fa-instagram"></i></a></li>
			<li><a href="https://www.facebook.com/monstream"><i class="fab fa-facebook"></i></a></li>
		</ul>
	</header>
	<main>
		<section>
			<h2>Ma chaîne</h2>
			<p>Bienvenue sur ma chaîne de streaming !</p>
			<p>Je suis un streamer passionné de jeux vidéo et de technologie, et j'aime partager mes aventures avec ma communauté.</p>
			<p>Vous pouvez me suivre sur les réseaux sociaux pour être informé de mes prochaines diffusions :</p>
			<ul>
				<li><a href="https://twitter.com/monstream">Twitter</a></li>
				<li><a href="https://www.instagram.com/monstream/">Instagram</a></li>
				<li><a href="https://www.facebook.com/monstream">Facebook</a></li>
			</ul>
		</section>
		<section>
			<h2>Liste des viewers</h2>
			@if (Model.Count > 0)
			{
				<form asp-action="List" asp-controller="Viewer">
					<select name="typeFiltre">
						<option value="tous">Tous</option>
						<option value="fidele">Les plus présents</option>
					</select>
					<button type="submit">Trier</button>
				</form>
				<table>
					<tr><th>Connecté</th><th>Photo</th><th>Pseudo</th></tr>
					@foreach (var follower in Model)
					{
						<tr>
							<td>@follower.EstConnecte</td>
							<td><img src=@follower.PhotoDeProfil width="40" height="40" /></td>
							<td>@follower.Surnom</td>
						</tr>
					}
				</table>
			}
			else
			{
				<h3>Rien à montrer</h3>
			}
		</section>
		<section>
			<h2>Mon dernier stream</h2>
			<div class="video-container">
				<iframe src="https://www.youtube.com/embed/DLzxrzFCyOs"></iframe>
			</div>
			<p>Voici le replay de mon dernier stream. J'espère que vous avez apprécié le contenu !</p>
			<p>N'hésitez pas à me laisser un commentaire pour me dire ce que vous avez aimé, et ce que je pourrais améliorer pour la prochaine fois.</p>
		</section>
		<section>
			<h2>Mon planning de diffusion</h2>
			<table>
				<thead>
					<tr>
						<th>Jour</th>
						<th>Heure</th>
						<th>Jeu</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Lundi</td>
						<td>20h-22h</td>
						<td>Fortnite</td>
					</tr>
					<tr>
						<td>Mercredi</td>
						<td>18h-20h</td>
						<td>League of Legends</td>
					</tr>
					<tr>
						<td>Vendredi</td>
						<td>21h-23h</td>
						<td>Among Us</td>
					</tr>
				</tbody>
			</table>
			<p>Voici les horaires et les jeux que je vais streamer cette semaine. J'espère vous voir nombreux pour suivre mes aventures !</p>
		</section>
	</main>
	<footer>
		<p>&copy; Mon Stream 2023 - Tous droits réservés</p>
	</footer>
</body>
</html>